"""create branches table

Revision ID: 141e952dfd4b
Revises: fe02fb3e00ce
Create Date: 2026-10-08 00:26:16.102423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141e952dfd4b'
down_revision: Union[str, Sequence[str], None] = 'fe02fb3e00ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_unique_constraint(
        'uq_businesses_id_organization',
        'businesses',
        ['id', 'organization_id']
    )

    op.create_table(
        'branches',
        sa.Column(
            'id',
            sa.UUID(),
            server_default=sa.text('uuidv7()'),
            nullable=False,
        ),
        sa.Column(
            'organization_id',
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            'business_id',
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            'code',
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            'name',
            sa.String(length=125),
            nullable=False,
        ),
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            'char_length(trim(code)) > 0',
            name='ck_branches_code_not_blank',
        ),
        sa.CheckConstraint(
            'char_length(trim(name)) > 0',
            name='ck_branches_name_not_blank',
        ),
        sa.ForeignKeyConstraint(
            ['business_id', 'organization_id'],
            ['businesses.id', 'businesses.organization_id'],
            name='fk_branches_business_organization',
            ondelete='RESTRICT',
        ),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organizations.id'],
            name='fk_branches_organization_id',
            ondelete='RESTRICT',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'business_id',
            'code',
            name='uq_branches_business_code',
        ),
        sa.UniqueConstraint(
            'id',
            'organization_id',
            name='uq_branches_id_organization',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branches')
    op.drop_constraint('uq_businesses_id_organization', 'businesses', type_='unique')
    
    # ### end Alembic commands ###
