"""create RBAC system

Revision ID: b1f11ebb758b
Revises: cec688b4d572
Create Date: 2026-10-08 11:06:41.583986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f11ebb758b'
down_revision: Union[str, Sequence[str], None] = 'cec688b4d572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=125), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(code)) > 0', name='ck_permissions_code_not_blank'),
    sa.CheckConstraint('char_length(trim(name)) > 0', name='ck_permissions_name_not_blank'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_permissions_code')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=125), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(code)) > 0', name='ck_roles_code_not_blank'),
    sa.CheckConstraint('char_length(trim(name)) > 0', name='ck_roles_name_not_blank'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_roles_organization_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_roles_id_organization'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_roles_organization_code')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_role_permissions_organization_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='fk_role_permissions_permission_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id', 'organization_id'], ['roles.id', 'roles.organization_id'], name='fk_role_permissions_role_organization', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    op.create_table('user_branch_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('revoked_by_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= assigned_at', name='ck_user_branch_roles_valid_revocation_date'),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name='fk_user_branch_roles_assigned_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['branch_id', 'organization_id'], ['branches.id', 'branches.organization_id'], name='fk_user_branch_roles_branch_organization', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_user_branch_roles_organization_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], name='fk_user_branch_roles_revoked_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id', 'organization_id'], ['roles.id', 'roles.organization_id'], name='fk_user_branch_roles_role_organization', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_branch_roles_user_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_user_branch_roles_active_assignment', 'user_branch_roles', ['user_id', 'branch_id', 'role_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_user_branch_roles_active_assignment', table_name='user_branch_roles', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('user_branch_roles')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
