"""create users table

Revision ID: cec688b4d572
Revises: 141e952dfd4b
Create Date: 2026-10-08 09:46:03.061874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec688b4d572'
down_revision: Union[str, Sequence[str], None] = '141e952dfd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(first_name)) > 0', name='ck_user_first_name_not_blank'),
    sa.CheckConstraint('char_length(trim(last_name)) > 0', name='ck_user_last_name_not_blank'),
    sa.CheckConstraint('char_length(trim(password_hash)) > 0', name='ck_user_password_hash_not_blank'),
    sa.CheckConstraint('char_length(trim(username)) > 0', name='ck_user_username_not_blank'),
    sa.CheckConstraint('email IS NULL OR char_length(trim(email)) > 0', name='ck_user_email_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_users_email_ci', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('ux_users_username_ci', 'users', [sa.literal_column('lower(username)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_users_username_ci', table_name='users')
    op.drop_index('ux_users_email_ci', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
